name = "gleam_evision_demo"
version = "0.2.2-rc0"
description = "A very early stage demo of gleam_evision."
licences = ["Apache-2.0"]
repository = { type = "github", user = "cocoa-xu", repo = "gleam_evision_demo" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/cocoa-xu" },
]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
gleam_otp = "~> 0.10"
gleam_erlang = ">= 0.25.0 and < 1.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
